# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build & Release

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
        cache: maven
        
    - name: Build with Maven
      run: mvn clean -B package --file pom.xml -DskipTests

    - name: Read version from pom.xml
      id: version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "version=v$VERSION" >> $GITHUB_OUTPUT

    - name: Prepare jar artifact
      run: |
        cp target/probsolve-*.jar probsolve-server-${{ steps.version.outputs.version }}

    - name: Build Docker Image
      run: |
       docker build -t qinloren/probsolve-server:${{ steps.version.outputs.version }}

    - name: Save Docker Image
      run: |
        docekr save qinloren/probsolve-server:${{ steps.version.outputs.version }} \
          -o probsolve-server-${{ steps.version.outputs.version }}.tar

    - name: Create Github Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.version.outputs.version }}
        name: ${{ steps.version.outputs.version }}
        generate_release_notes: true
        files: |
          probsolve-server-${{ steps.version.outputs.version }}.jar
          probsolve-server-${{ steps.version.outputs.version }}.tar
